include(joinpath((@__DIR__), "Equatorial.jl"))
include(joinpath((@__DIR__), "JuKeBOX.jl"))
include(joinpath((@__DIR__), "EqDualCone.jl"))
include(joinpath((@__DIR__), "GpuizedModel.jl"))
include(joinpath((@__DIR__), "GpuizedBlurredModel.jl"))
include(joinpath((@__DIR__), "defaults.jl"))
include(abspath(joinpath((@__DIR__), "vidawrappers.jl")))